/**
 * 위치/환경 매핑 데이터
 * 한국어 키워드 → 영어 ComfyUI 프롬프트 매핑
 */

export const LOCATION_MAPPINGS = {
  // === 1. 주거공간 ===
  '집에서': 'at home, comfortable indoor setting, cozy residential interior',
  '집': 'at home, comfortable indoor setting, cozy residential interior',
  '방에서': 'in bedroom, private cozy room, intimate indoor space',
  '방': 'in bedroom, private cozy room, intimate indoor space',
  '거실': 'in living room, comfortable home interior, family space',
  '거실에서': 'in living room, comfortable home interior, family space',
  '침실': 'in bedroom, private sleeping room, intimate space',
  '침실에서': 'in bedroom, private sleeping room, intimate space',
  '부엌': 'in kitchen, home cooking area, warm domestic interior',
  '부엌에서': 'in kitchen, home cooking area, warm domestic interior',
  '화장실': 'in bathroom, private home interior, clean modern space',
  '욕실': 'in bathroom, private home interior, clean modern space',
  '베란다': 'on balcony, home outdoor space, comfortable terrace',
  '테라스': 'on terrace, outdoor home extension, comfortable patio',
  '마당': 'in home garden, residential yard, private outdoor space',
  '아파트': 'in apartment, modern residential interior, urban living space',
  '빌라': 'in villa, residential building interior, comfortable living space',
  
  // === 2. 상업공간 (핵심 누락 해결) ===
  '매장': 'in retail store, commercial indoor space, shopping environment',
  '매장에서': 'in retail store, commercial indoor space, shopping environment',
  '상점': 'in store, shopping environment, commercial interior',
  '상점에서': 'in store, shopping environment, commercial interior',
  '쇼핑몰': 'in shopping mall, large commercial complex, modern retail environment',
  '쇼핑센터': 'in shopping center, commercial complex, retail environment',
  '백화점': 'in department store, luxury shopping environment, upscale retail interior',
  '백화점에서': 'in department store, luxury shopping environment, upscale retail interior',
  '마트': 'in supermarket, grocery store interior, commercial shopping space',
  '대형마트': 'in large supermarket, spacious retail interior, commercial environment',
  '편의점': 'in convenience store, small retail space, modern commercial interior',
  '편의점에서': 'in convenience store, small retail space, modern commercial interior',
  '수영복매장': 'in swimwear store, fashion retail interior, clothing shop environment',
  '수영복 매장': 'in swimwear store, fashion retail interior, clothing shop environment',
  '옷가게': 'in clothing store, fashion retail interior, apparel shop',
  '의류매장': 'in clothing store, fashion retail interior, apparel shop environment',
  '신발가게': 'in shoe store, footwear retail interior, commercial shopping space',
  '화장품가게': 'in cosmetics store, beauty retail interior, modern commercial space',
  '서점': 'in bookstore, literary retail environment, quiet commercial interior',
  '서점에서': 'in bookstore, literary retail environment, quiet commercial interior',
  '음반가게': 'in music store, entertainment retail interior, media shop environment',
  '전자제품매장': 'in electronics store, tech retail interior, modern commercial space',
  '가구점': 'in furniture store, home goods retail interior, spacious commercial environment',
  '꽃집': 'in flower shop, floral retail interior, colorful commercial space',
  '약국': 'in pharmacy, medical retail interior, clean commercial environment',
  '빵집': 'in bakery, food retail interior, warm commercial kitchen environment',
  '제과점': 'in bakery, confectionery retail interior, sweet shop environment',
  
  // === 3. 음식점/카페 ===
  '카페에서': 'in a cozy cafe, warm coffee shop atmosphere, comfortable seating',
  '카페': 'in a cozy cafe, warm coffee shop atmosphere, comfortable seating',
  '커피숍': 'in coffee shop, warm cafe interior, comfortable seating area',
  '찻집': 'in tea house, traditional cafe interior, cozy seating environment',
  '식당에서': 'in restaurant, dining atmosphere, warm interior lighting',
  '식당': 'in restaurant, dining atmosphere, warm interior lighting',
  '음식점': 'in restaurant, dining atmosphere, warm interior lighting',
  '레스토랑': 'in restaurant, upscale dining environment, elegant interior',
  '패스트푸드점': 'in fast food restaurant, casual dining interior, modern commercial space',
  '패밀리레스토랑': 'in family restaurant, comfortable dining environment, warm interior',
  '한식당': 'in Korean restaurant, traditional dining atmosphere, cultural interior',
  '중식당': 'in Chinese restaurant, oriental dining environment, cultural decor',
  '일식당': 'in Japanese restaurant, minimalist dining interior, zen atmosphere',
  '양식당': 'in western restaurant, elegant dining environment, sophisticated interior',
  '치킨집': 'in chicken restaurant, casual dining interior, comfortable food environment',
  '피자집': 'in pizza restaurant, casual dining interior, warm food environment',
  '햄버거집': 'in burger restaurant, casual dining interior, modern fast food environment',
  '술집': 'in bar, casual drinking environment, warm social interior',
  '주점': 'in pub, traditional drinking environment, cozy social space',
  '바': 'in bar, modern drinking environment, sophisticated interior',
  
  // === 4. 직장공간 ===
  '사무실에서': 'in the office, professional workplace environment',
  '사무실': 'in the office, professional workplace environment',
  '회사': 'in the office, professional workplace environment',
  '회사에서': 'in the office, professional workplace environment',
  '회의실': 'in meeting room, professional conference space, business environment',
  '회의실에서': 'in meeting room, professional conference space, business environment',
  '사무실책상': 'at office desk, professional workspace, business interior',
  '책상': 'at desk, workspace environment, study or office interior',
  '책상앞': 'at desk, workspace environment, study or office interior',
  '작업실': 'in workshop, creative workspace, professional studio environment',
  '스튜디오': 'in studio, creative workspace, professional artistic environment',
  '공장': 'in factory, industrial environment, manufacturing workspace',
  '창고': 'in warehouse, storage facility, industrial interior space',
  
  // === 5. 교육공간 ===
  '학교에서': 'at school, educational setting, classroom environment',
  '학교': 'at school, educational setting, classroom environment',
  '교실': 'in classroom, educational interior, learning environment',
  '교실에서': 'in classroom, educational interior, learning environment',
  '강의실': 'in lecture hall, academic environment, educational interior',
  '도서관': 'in library, quiet study environment, scholarly atmosphere',
  '도서관에서': 'in library, quiet study environment, scholarly atmosphere',
  '독서실': 'in study room, quiet learning environment, academic interior',
  '실험실': 'in laboratory, scientific research environment, modern academic interior',
  '컴퓨터실': 'in computer lab, technology learning environment, modern educational space',
  '음악실': 'in music room, creative learning environment, artistic interior',
  '미술실': 'in art room, creative studio environment, artistic learning space',
  '체육관': 'in gym, fitness facility, workout environment',
  '운동장': 'at sports field, outdoor athletic venue',
  '대학교': 'at university, higher education environment, academic campus interior',
  '대학': 'at university, higher education environment, academic campus interior',
  '고등학교': 'at high school, secondary education environment, school interior',
  '중학교': 'at middle school, educational environment, school interior',
  '초등학교': 'at elementary school, primary education environment, school interior',
  
  // === 6. 의료/건강 ===
  '병원': 'in hospital, clean medical environment, professional setting',
  '병원에서': 'in hospital, clean medical environment, professional setting',
  '치과': 'in dental clinic, medical environment, clean professional interior',
  '안과': 'in eye clinic, medical environment, clean professional interior',
  '한의원': 'in oriental medicine clinic, traditional medical environment',
  '클리닉': 'in medical clinic, healthcare environment, professional interior',
  '응급실': 'in emergency room, medical environment, urgent care interior',
  '수술실': 'in operating room, sterile medical environment, professional healthcare interior',
  '약국에서': 'in pharmacy, medical retail interior, clean commercial environment',
  
  // === 7. 숙박/호텔 ===
  '호텔': 'in hotel, luxury accommodation setting',
  '호텔에서': 'in hotel, luxury accommodation setting',
  '호텔방': 'in hotel room, comfortable accommodation interior, hospitality environment',
  '모텔': 'in motel, accommodation interior, comfortable lodging environment',
  '펜션': 'in pension, vacation rental interior, comfortable accommodation',
  '민박': 'in guesthouse, traditional accommodation, comfortable lodging interior',
  '게스트하우스': 'in guesthouse, budget accommodation, social lodging environment',
  '리조트': 'in resort, luxury vacation environment, upscale hospitality interior',
  '콘도': 'in condo, vacation accommodation, comfortable residential interior',
  
  // === 8. 엔터테인먼트 ===
  '영화관': 'in cinema, movie theater, entertainment venue',
  '영화관에서': 'in cinema, movie theater, entertainment venue',
  '극장': 'in theater, performance venue, cultural entertainment space',
  '콘서트홀': 'in concert hall, music venue, performance interior',
  '노래방': 'in karaoke room, entertainment space, private singing room',
  'KTV': 'in karaoke room, entertainment space, private singing room',
  '게임방': 'in gaming center, entertainment facility, recreational interior',
  'PC방': 'in PC cafe, gaming environment, computer entertainment space',
  '만화방': 'in comic book cafe, reading entertainment space, cozy interior',
  '당구장': 'in billiards hall, recreational facility, entertainment interior',
  '볼링장': 'in bowling alley, recreational facility, entertainment venue',
  
  // === 9. 자연공간 ===
  '공원에서': 'in the park, outdoor garden setting, natural green environment',
  '공원': 'in the park, outdoor garden setting, natural green environment',
  '해변에서': 'on the beach, seaside atmosphere, ocean view background',
  '해변': 'on the beach, seaside atmosphere, ocean view background',
  '바다': 'on the beach, seaside atmosphere, ocean view background',
  '바다에서': 'on the beach, seaside atmosphere, ocean view background',
  '바닷가': 'on the beach, seaside atmosphere, ocean view background',
  '산에서': 'in the mountains, highland setting, scenic mountain view',
  '산': 'in the mountains, highland setting, scenic mountain view',
  '등산로': 'on hiking trail, mountain path, natural outdoor environment',
  '숲에서': 'in the forest, woodland scene, natural tree background',
  '숲': 'in the forest, woodland scene, natural tree background',
  '강가': 'by the river, waterside setting, peaceful nature scene',
  '강': 'by the river, waterside setting, peaceful nature scene',
  '강에서': 'by the river, waterside setting, peaceful nature scene',
  '호수': 'by the lake, serene water view, tranquil natural setting',
  '호수에서': 'by the lake, serene water view, tranquil natural setting',
  '계곡': 'in valley, natural mountain stream, peaceful nature environment',
  '폭포': 'near waterfall, natural scenic environment, refreshing nature setting',
  '들판': 'in field, open grassland, rural natural environment',
  '농장': 'at farm, rural agricultural setting, countryside environment',
  '목장': 'at ranch, pastoral countryside, agricultural natural setting',
  '동물원': 'at zoo, wildlife park, outdoor animal environment',
  '식물원': 'in botanical garden, greenhouse environment, natural plant setting',
  '수목원': 'in arboretum, tree garden, natural botanical environment',
  
  // === 10. 도시/거리 ===
  '길에서': 'on the street, urban outdoor setting, city walkway',
  '길': 'on the street, urban outdoor setting, city walkway',
  '거리': 'on the street, urban outdoor setting, city walkway',
  '거리에서': 'on the street, urban outdoor setting, city walkway',
  '도시에서': 'in the city, urban environment, modern cityscape',
  '도시': 'in the city, urban environment, modern cityscape',
  '시내': 'in downtown, urban city center, bustling city environment',
  '시내에서': 'in downtown, urban city center, bustling city environment',
  '광장': 'in plaza, public square, urban outdoor gathering space',
  '광장에서': 'in plaza, public square, urban outdoor gathering space',
  '시장': 'at market, bustling outdoor marketplace, vendor stalls',
  '시장에서': 'at market, bustling outdoor marketplace, vendor stalls',
  '전통시장': 'at traditional market, cultural marketplace, authentic vendor environment',
  '놀이터': 'at playground, outdoor recreational area',
  '놀이터에서': 'at playground, outdoor recreational area',
  '정원': 'in garden, beautiful outdoor landscape, flowering plants',
  '정원에서': 'in garden, beautiful outdoor landscape, flowering plants',
  '운동장': 'at sports field, outdoor athletic venue',
  '운동장에서': 'at sports field, outdoor athletic venue',
  '주차장': 'in parking lot, outdoor urban space, concrete environment',
  '버스정류장': 'at bus stop, urban transit point, public transportation area',
  '지하보도': 'in underground passage, urban tunnel, city infrastructure',
  '다리': 'on bridge, elevated urban structure, city landmark',
  '다리에서': 'on bridge, elevated urban structure, city landmark',
  '터널': 'in tunnel, enclosed passage, urban infrastructure interior',
  
  // === 11. 문화공간 ===
  '박물관': 'in museum, cultural exhibition space',
  '박물관에서': 'in museum, cultural exhibition space',
  '미술관': 'in art gallery, cultural venue, exhibition space',
  '미술관에서': 'in art gallery, cultural venue, exhibition space',
  '전시관': 'in exhibition hall, cultural display space, artistic venue',
  '전시장': 'in exhibition space, cultural display area, artistic environment',
  '갤러리': 'in art gallery, intimate cultural space, artistic venue',
  '문화센터': 'in cultural center, community arts space, educational cultural venue',
  '공연장': 'in performance venue, cultural entertainment space',
  '무대': 'on stage, performance venue, theatrical setting',
  '무대에서': 'on stage, performance venue, theatrical setting',
  '콘서트': 'at concert, music venue, entertainment atmosphere',
  '콘서트홀': 'in concert hall, music venue, performance interior',
  '오페라하우스': 'in opera house, classical performance venue, elegant cultural interior',
  '연극장': 'in theater, dramatic performance venue, cultural entertainment space',
  '아트센터': 'in arts center, creative cultural space, modern artistic venue',
  
  // === 12. 스포츠공간 ===
  '체육관': 'in gym, fitness facility, workout environment',
  '체육관에서': 'in gym, fitness facility, workout environment',
  '헬스장': 'in fitness gym, workout facility, exercise environment',
  '헬스클럽': 'in health club, premium fitness facility, exercise environment',
  '수영장': 'at swimming pool, aquatic facility, recreational water area',
  '수영장에서': 'at swimming pool, aquatic facility, recreational water area',
  '골프장': 'at golf course, outdoor sports facility, green recreational environment',
  '골프장에서': 'at golf course, outdoor sports facility, green recreational environment',
  '테니스장': 'at tennis court, sports facility, athletic environment',
  '배드민턴장': 'at badminton court, indoor sports facility, athletic environment',
  '농구장': 'at basketball court, sports facility, athletic environment',
  '축구장': 'at soccer field, outdoor sports venue, athletic environment',
  '야구장': 'at baseball stadium, sports venue, athletic environment',
  '볼링장': 'in bowling alley, recreational facility, entertainment venue',
  '당구장': 'in billiards hall, recreational facility, entertainment interior',
  '탁구장': 'at ping pong facility, indoor sports environment, recreational venue',
  '스키장': 'at ski resort, winter sports facility, snowy mountain environment',
  '아이스링크': 'at ice rink, winter sports facility, indoor ice environment',
  '놀이공원': 'at amusement park, theme park, recreational venue',
  '놀이공원에서': 'at amusement park, theme park, recreational venue',
  '워터파크': 'at water park, aquatic recreational facility, fun water environment',
  '사우나': 'in sauna, wellness facility, relaxation interior',
  '찜질방': 'in jjimjilbang, Korean spa facility, wellness relaxation interior',
  '마사지샵': 'in massage parlor, wellness facility, relaxation treatment interior',
  
  // === 13. 교통공간 (세분화) ===
  '차에서': 'in car, vehicle interior, traveling atmosphere',
  '차': 'in car, vehicle interior, traveling atmosphere',
  '택시': 'in taxi, urban transport interior, city travel environment',
  '택시에서': 'in taxi, urban transport interior, city travel environment',
  '지하철': 'in subway, underground transit, commuter setting',
  '지하철에서': 'in subway, underground transit, commuter setting',
  '지하철역': 'in subway station, urban transit hub, underground public space',
  '버스': 'in bus, public transportation interior',
  '버스에서': 'in bus, public transportation interior',
  '버스터미널': 'in bus terminal, transportation hub, travel facility',
  '기차': 'in train, railway travel setting',
  '기차에서': 'in train, railway travel setting',
  '기차역': 'in train station, transportation hub, travel facility',
  'KTX': 'in high-speed train, modern rail travel, comfortable transport interior',
  '지하철역사': 'in subway concourse, underground public space, transit facility',
  '비행기': 'in airplane, aircraft cabin, travel atmosphere',
  '비행기에서': 'in airplane, aircraft cabin, travel atmosphere',
  '공항': 'in airport, aviation facility, travel hub environment',
  '공항에서': 'in airport, aviation facility, travel hub environment',
  '공항터미널': 'in airport terminal, aviation facility, international travel hub',
  '대합실': 'in waiting room, transportation facility, travel waiting area',
  '승강장': 'on platform, transportation station, boarding area',
  '매표소': 'at ticket office, transportation facility, travel service area',
  '출입국사무소': 'in immigration office, government facility, official administrative interior',
  '세관': 'in customs, government facility, official border control interior',
  '면세점': 'in duty-free shop, airport retail, travel shopping environment',
  '면세점에서': 'in duty-free shop, airport retail, travel shopping environment',
  '휴게소': 'at rest stop, highway service area, travel break facility',
  '주유소': 'at gas station, automotive service facility, roadside commercial space',
  
  
  // === 14. 시간대/분위기 ===
  '밤에': 'at night, nighttime atmosphere, evening setting',
  '밤': 'at night, nighttime atmosphere, evening setting',
  '새벽': 'at dawn, early morning atmosphere, sunrise setting',
  '새벽에': 'at dawn, early morning atmosphere, sunrise setting',
  '아침에': 'in the morning, dawn lighting, fresh morning atmosphere',
  '아침': 'in the morning, dawn lighting, fresh morning atmosphere',
  '오전': 'in the morning, morning hours, fresh daytime atmosphere',
  '점심': 'at midday, noon atmosphere, bright daylight',
  '점심시간': 'at lunchtime, midday atmosphere, bright daylight',
  '오후': 'in the afternoon, daytime atmosphere, comfortable lighting',
  '저녁': 'in the evening, sunset atmosphere, golden hour lighting',
  '저녁에': 'in the evening, sunset atmosphere, golden hour lighting',
  '해질녕': 'at sunset, golden hour, romantic evening atmosphere',
  '해돋이': 'at sunrise, dawn break, fresh morning atmosphere',
  '심야': 'late at night, midnight atmosphere, quiet nocturnal setting',
  '자정': 'at midnight, late night atmosphere, quiet nocturnal environment',
  
  // === 15. 날씨/기후 ===
  '비오는': 'in rain, rainy weather atmosphere, wet environment',
  '비오는날': 'in rainy weather, wet atmospheric environment, stormy setting',
  '비': 'in rain, rainy weather atmosphere, wet environment',
  '비에서': 'in rain, rainy weather atmosphere, wet environment',
  '눈오는': 'in snow, snowy weather, winter atmosphere',
  '눈오는날': 'in snowy weather, winter atmospheric environment, cold setting',
  '눈': 'in snow, snowy weather, winter atmosphere',
  '눈에서': 'in snow, snowy weather, winter atmosphere',
  '맑은': 'in clear weather, bright sunny atmosphere',
  '맑은날': 'in clear sunny weather, bright atmospheric environment',
  '맑은하늘': 'under clear sky, bright sunny atmosphere, pleasant weather',
  '흐린': 'in cloudy weather, overcast atmosphere',
  '흐린날': 'in cloudy weather, overcast atmospheric environment',
  '흐린하늘': 'under cloudy sky, overcast atmosphere, moody weather',
  '바람부는': 'in windy weather, breezy atmosphere, dynamic air environment',
  '바람부는날': 'in windy weather, breezy atmospheric environment',
  '안개끼인': 'in foggy weather, misty atmosphere, mysterious environment',
  '안개': 'in fog, misty atmospheric environment, mysterious setting',
  '천둥': 'in thunder storm, dramatic weather atmosphere, powerful environment',
  '번개': 'in lightning storm, dramatic atmospheric environment, intense weather',
  '폭우': 'in heavy rain, stormy weather atmosphere, intense precipitation',
  '폭설': 'in blizzard, severe winter weather, harsh snowy environment',
  '무더위': 'in hot weather, humid summer atmosphere, warm environment',
  '추위': 'in cold weather, chilly atmosphere, cool environment',
  '습한': 'in humid weather, moist atmosphere, tropical environment',
  '건조한': 'in dry weather, arid atmosphere, desert-like environment',
  
  // === 16. 계절 ===
  '봄': 'in spring, cherry blossom season, fresh green atmosphere',
  '봄에': 'in spring, cherry blossom season, fresh green atmosphere',
  '봄철': 'in spring season, blooming flowers, fresh green environment',
  '여름': 'in summer, warm season, bright sunny atmosphere',
  '여름에': 'in summer, warm season, bright sunny atmosphere',
  '여름철': 'in summer season, hot sunny weather, vacation atmosphere',
  '가을': 'in autumn, fall season, colorful leaves atmosphere',
  '가을에': 'in autumn, fall season, colorful leaves atmosphere',
  '가을철': 'in fall season, autumn foliage, harvest atmosphere',
  '단풍': 'in autumn foliage, colorful fall leaves, seasonal atmosphere',
  '겨울': 'in winter, cold season, snowy atmosphere',
  '겨울에': 'in winter, cold season, snowy atmosphere',
  '겨울철': 'in winter season, cold snowy weather, quiet atmosphere',
  '연말': 'at year end, winter holiday season, festive atmosphere',
  '연초': 'at new year, winter holiday season, celebratory atmosphere',
  '크리스마스': 'at Christmas, winter holiday atmosphere, festive decoration environment',
  '설날': 'at Lunar New Year, traditional Korean holiday, cultural celebration atmosphere',
  '추석': 'at Chuseok, Korean harvest festival, traditional cultural atmosphere',
  
  // === 17. 특수한 상황/이벤트 ===
  '결혼식': 'at wedding ceremony, elegant celebration venue, romantic formal setting',
  '결혼식장': 'in wedding venue, elegant celebration space, romantic formal interior',
  '생일파티': 'at birthday party, celebration venue, festive party atmosphere',
  '파티장': 'at party venue, celebration space, festive social environment',
  '축제': 'at festival, outdoor celebration, cultural event atmosphere',
  '축제장': 'at festival ground, outdoor celebration space, cultural event environment',
  '회사회식': 'at company dinner, business social event, professional gathering',
  '회식': 'at dinner party, social dining event, elegant gathering atmosphere',
  '유치원': 'in kindergarten, early childhood education, playful learning environment',
  '어린이집': 'in daycare, childcare facility, nurturing educational interior',
  '진료소': 'in medical clinic, healthcare facility, professional treatment environment',
  '진료소에서': 'in medical clinic, healthcare facility, professional treatment environment',
  '대기실': 'in waiting room, comfortable seating area, calm interior environment',
  '상담실': 'in counseling room, private consultation space, comfortable therapy interior',
  '회의실': 'in meeting room, professional conference space, business environment',
  '인터뷰실': 'in interview room, professional meeting space, formal business interior',
  '심사실': 'in examination room, evaluation space, formal assessment interior',
  '결제대': 'at checkout counter, retail payment area, commercial service point',
  '계산대': 'at cashier counter, retail payment point, commercial checkout area',
  '따뜻한': 'in warm atmosphere, comfortable cozy environment, gentle ambiance',
  '편안한': 'in comfortable setting, relaxing cozy environment, peaceful atmosphere',
  '아늩한': 'in cozy atmosphere, intimate comfortable setting, warm environment',
  '로맨틱한': 'in romantic setting, intimate lovely atmosphere, charming environment',
  
  // === 18. 기본값 ===
  'default': 'in a comfortable indoor setting, soft natural lighting'
} as const;

export type LocationKeyword = keyof typeof LOCATION_MAPPINGS;